// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCardServiceInterface creates a new instance of MockCardServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCardServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCardServiceInterface {
	mock := &MockCardServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCardServiceInterface is an autogenerated mock type for the CardServiceInterface type
type MockCardServiceInterface struct {
	mock.Mock
}

type MockCardServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCardServiceInterface) EXPECT() *MockCardServiceInterface_Expecter {
	return &MockCardServiceInterface_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockCardServiceInterface
func (_mock *MockCardServiceInterface) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockCardServiceInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCardServiceInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCardServiceInterface_Expecter) Start(ctx interface{}) *MockCardServiceInterface_Start_Call {
	return &MockCardServiceInterface_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockCardServiceInterface_Start_Call) Run(run func(ctx context.Context)) *MockCardServiceInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCardServiceInterface_Start_Call) Return() *MockCardServiceInterface_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCardServiceInterface_Start_Call) RunAndReturn(run func(ctx context.Context)) *MockCardServiceInterface_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockCardServiceInterface
func (_mock *MockCardServiceInterface) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCardServiceInterface_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockCardServiceInterface_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockCardServiceInterface_Expecter) Stop() *MockCardServiceInterface_Stop_Call {
	return &MockCardServiceInterface_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockCardServiceInterface_Stop_Call) Run(run func()) *MockCardServiceInterface_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCardServiceInterface_Stop_Call) Return(err error) *MockCardServiceInterface_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCardServiceInterface_Stop_Call) RunAndReturn(run func() error) *MockCardServiceInterface_Stop_Call {
	_c.Call.Return(run)
	return _c
}
