// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNetworkingClient creates a new instance of MockNetworkingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworkingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworkingClient {
	mock := &MockNetworkingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNetworkingClient is an autogenerated mock type for the NetworkingClient type
type MockNetworkingClient struct {
	mock.Mock
}

type MockNetworkingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetworkingClient) EXPECT() *MockNetworkingClient_Expecter {
	return &MockNetworkingClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockNetworkingClient
func (_mock *MockNetworkingClient) Get(url string) ([]byte, int, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, int, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) int); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(url)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNetworkingClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNetworkingClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
func (_e *MockNetworkingClient_Expecter) Get(url interface{}) *MockNetworkingClient_Get_Call {
	return &MockNetworkingClient_Get_Call{Call: _e.mock.On("Get", url)}
}

func (_c *MockNetworkingClient_Get_Call) Run(run func(url string)) *MockNetworkingClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNetworkingClient_Get_Call) Return(body []byte, status int, err error) *MockNetworkingClient_Get_Call {
	_c.Call.Return(body, status, err)
	return _c
}

func (_c *MockNetworkingClient_Get_Call) RunAndReturn(run func(url string) ([]byte, int, error)) *MockNetworkingClient_Get_Call {
	_c.Call.Return(run)
	return _c
}
