// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSleepableInterface creates a new instance of MockSleepableInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSleepableInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSleepableInterface {
	mock := &MockSleepableInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSleepableInterface is an autogenerated mock type for the SleepableInterface type
type MockSleepableInterface struct {
	mock.Mock
}

type MockSleepableInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSleepableInterface) EXPECT() *MockSleepableInterface_Expecter {
	return &MockSleepableInterface_Expecter{mock: &_m.Mock}
}

// Duration provides a mock function for the type MockSleepableInterface
func (_mock *MockSleepableInterface) Duration() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Duration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockSleepableInterface_Duration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Duration'
type MockSleepableInterface_Duration_Call struct {
	*mock.Call
}

// Duration is a helper method to define mock.On call
func (_e *MockSleepableInterface_Expecter) Duration() *MockSleepableInterface_Duration_Call {
	return &MockSleepableInterface_Duration_Call{Call: _e.mock.On("Duration")}
}

func (_c *MockSleepableInterface_Duration_Call) Run(run func()) *MockSleepableInterface_Duration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSleepableInterface_Duration_Call) Return(duration time.Duration) *MockSleepableInterface_Duration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockSleepableInterface_Duration_Call) RunAndReturn(run func() time.Duration) *MockSleepableInterface_Duration_Call {
	_c.Call.Return(run)
	return _c
}

// Sleep provides a mock function for the type MockSleepableInterface
func (_mock *MockSleepableInterface) Sleep() (func() bool, <-chan time.Time) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sleep")
	}

	var r0 func() bool
	var r1 <-chan time.Time
	if returnFunc, ok := ret.Get(0).(func() (func() bool, <-chan time.Time)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() func() bool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() <-chan time.Time); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan time.Time)
		}
	}
	return r0, r1
}

// MockSleepableInterface_Sleep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sleep'
type MockSleepableInterface_Sleep_Call struct {
	*mock.Call
}

// Sleep is a helper method to define mock.On call
func (_e *MockSleepableInterface_Expecter) Sleep() *MockSleepableInterface_Sleep_Call {
	return &MockSleepableInterface_Sleep_Call{Call: _e.mock.On("Sleep")}
}

func (_c *MockSleepableInterface_Sleep_Call) Run(run func()) *MockSleepableInterface_Sleep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSleepableInterface_Sleep_Call) Return(stop func() bool, done <-chan time.Time) *MockSleepableInterface_Sleep_Call {
	_c.Call.Return(stop, done)
	return _c
}

func (_c *MockSleepableInterface_Sleep_Call) RunAndReturn(run func() (func() bool, <-chan time.Time)) *MockSleepableInterface_Sleep_Call {
	_c.Call.Return(run)
	return _c
}
