// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// Done provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockServiceInterface_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockServiceInterface_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockServiceInterface_Expecter) Done() *MockServiceInterface_Done_Call {
	return &MockServiceInterface_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockServiceInterface_Done_Call) Run(run func()) *MockServiceInterface_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceInterface_Done_Call) Return(valCh <-chan struct{}) *MockServiceInterface_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockServiceInterface_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockServiceInterface_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceInterface_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockServiceInterface_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockServiceInterface_Expecter) Err() *MockServiceInterface_Err_Call {
	return &MockServiceInterface_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockServiceInterface_Err_Call) Run(run func()) *MockServiceInterface_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceInterface_Err_Call) Return(err error) *MockServiceInterface_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceInterface_Err_Call) RunAndReturn(run func() error) *MockServiceInterface_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Start(ctx context.Context) func() {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 func()
	if returnFunc, ok := ret.Get(0).(func(context.Context) func()); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}
	return r0
}

// MockServiceInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockServiceInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceInterface_Expecter) Start(ctx interface{}) *MockServiceInterface_Start_Call {
	return &MockServiceInterface_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockServiceInterface_Start_Call) Run(run func(ctx context.Context)) *MockServiceInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Start_Call) Return(stop func()) *MockServiceInterface_Start_Call {
	_c.Call.Return(stop)
	return _c
}

func (_c *MockServiceInterface_Start_Call) RunAndReturn(run func(ctx context.Context) func()) *MockServiceInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}
