// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package justtcgmocks

import (
	"context"

	"github.com/ianhecker/pokemon-tcg-services/internal/justtcg/v1/cards"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIClientInterface creates a new instance of MockAPIClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIClientInterface {
	mock := &MockAPIClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIClientInterface is an autogenerated mock type for the APIClientInterface type
type MockAPIClientInterface struct {
	mock.Mock
}

type MockAPIClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIClientInterface) EXPECT() *MockAPIClientInterface_Expecter {
	return &MockAPIClientInterface_Expecter{mock: &_m.Mock}
}

// GetPricing provides a mock function for the type MockAPIClientInterface
func (_mock *MockAPIClientInterface) GetPricing(ctx context.Context, ID cards.TCGPlayerID) (cards.Card, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetPricing")
	}

	var r0 cards.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cards.TCGPlayerID) (cards.Card, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cards.TCGPlayerID) cards.Card); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(cards.Card)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cards.TCGPlayerID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIClientInterface_GetPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricing'
type MockAPIClientInterface_GetPricing_Call struct {
	*mock.Call
}

// GetPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - ID cards.TCGPlayerID
func (_e *MockAPIClientInterface_Expecter) GetPricing(ctx interface{}, ID interface{}) *MockAPIClientInterface_GetPricing_Call {
	return &MockAPIClientInterface_GetPricing_Call{Call: _e.mock.On("GetPricing", ctx, ID)}
}

func (_c *MockAPIClientInterface_GetPricing_Call) Run(run func(ctx context.Context, ID cards.TCGPlayerID)) *MockAPIClientInterface_GetPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cards.TCGPlayerID
		if args[1] != nil {
			arg1 = args[1].(cards.TCGPlayerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIClientInterface_GetPricing_Call) Return(card cards.Card, err error) *MockAPIClientInterface_GetPricing_Call {
	_c.Call.Return(card, err)
	return _c
}

func (_c *MockAPIClientInterface_GetPricing_Call) RunAndReturn(run func(ctx context.Context, ID cards.TCGPlayerID) (cards.Card, error)) *MockAPIClientInterface_GetPricing_Call {
	_c.Call.Return(run)
	return _c
}
