// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package justtcgmocks

import (
	"context"

	"github.com/ianhecker/pokemon-tcg-services/internal/justtcg"
	"github.com/ianhecker/pokemon-tcg-services/internal/justtcg/v1/cards"
	"github.com/ianhecker/pokemon-tcg-services/internal/retry"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// GetPricing provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) GetPricing(ctx context.Context, ID cards.TCGPlayerID) (cards.Card, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetPricing")
	}

	var r0 cards.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cards.TCGPlayerID) (cards.Card, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cards.TCGPlayerID) cards.Card); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(cards.Card)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cards.TCGPlayerID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInterface_GetPricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPricing'
type MockClientInterface_GetPricing_Call struct {
	*mock.Call
}

// GetPricing is a helper method to define mock.On call
//   - ctx context.Context
//   - ID cards.TCGPlayerID
func (_e *MockClientInterface_Expecter) GetPricing(ctx interface{}, ID interface{}) *MockClientInterface_GetPricing_Call {
	return &MockClientInterface_GetPricing_Call{Call: _e.mock.On("GetPricing", ctx, ID)}
}

func (_c *MockClientInterface_GetPricing_Call) Run(run func(ctx context.Context, ID cards.TCGPlayerID)) *MockClientInterface_GetPricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cards.TCGPlayerID
		if args[1] != nil {
			arg1 = args[1].(cards.TCGPlayerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientInterface_GetPricing_Call) Return(card cards.Card, err error) *MockClientInterface_GetPricing_Call {
	_c.Call.Return(card, err)
	return _c
}

func (_c *MockClientInterface_GetPricing_Call) RunAndReturn(run func(ctx context.Context, ID cards.TCGPlayerID) (cards.Card, error)) *MockClientInterface_GetPricing_Call {
	_c.Call.Return(run)
	return _c
}

// MakeRetryFunc provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) MakeRetryFunc(url string) (*justtcg.Result, retry.RetryFunc) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for MakeRetryFunc")
	}

	var r0 *justtcg.Result
	var r1 retry.RetryFunc
	if returnFunc, ok := ret.Get(0).(func(string) (*justtcg.Result, retry.RetryFunc)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *justtcg.Result); ok {
		r0 = returnFunc(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*justtcg.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) retry.RetryFunc); ok {
		r1 = returnFunc(url)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(retry.RetryFunc)
		}
	}
	return r0, r1
}

// MockClientInterface_MakeRetryFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeRetryFunc'
type MockClientInterface_MakeRetryFunc_Call struct {
	*mock.Call
}

// MakeRetryFunc is a helper method to define mock.On call
//   - url string
func (_e *MockClientInterface_Expecter) MakeRetryFunc(url interface{}) *MockClientInterface_MakeRetryFunc_Call {
	return &MockClientInterface_MakeRetryFunc_Call{Call: _e.mock.On("MakeRetryFunc", url)}
}

func (_c *MockClientInterface_MakeRetryFunc_Call) Run(run func(url string)) *MockClientInterface_MakeRetryFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientInterface_MakeRetryFunc_Call) Return(result *justtcg.Result, retryFunc retry.RetryFunc) *MockClientInterface_MakeRetryFunc_Call {
	_c.Call.Return(result, retryFunc)
	return _c
}

func (_c *MockClientInterface_MakeRetryFunc_Call) RunAndReturn(run func(url string) (*justtcg.Result, retry.RetryFunc)) *MockClientInterface_MakeRetryFunc_Call {
	_c.Call.Return(run)
	return _c
}
